// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/button.vue')['default']
    NoteTab: typeof import('./components/note-tab.vue')['default']
    NoteTitle: typeof import('./components/note-title.vue')['default']
    TheEditor: typeof import('./components/the-editor.vue')['default']
    TheNavbar: typeof import('./components/the-navbar/index.vue')['default']
    ThePreview: typeof import('./components/the-preview.vue')['default']
    UserArea: typeof import('./components/the-navbar/user-area.vue')['default']
  }
}

export { }
