// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NoteTab: typeof import('./components/note-tab.vue')['default']
    NoteTitle: typeof import('./components/note-title.vue')['default']
    TheCurrentNoteTitle: typeof import('./components/the-current-note-title.vue')['default']
    TheEditor: typeof import('./components/the-editor.vue')['default']
    TheNavbar: typeof import('./components/the-navbar.vue')['default']
    ThePreview: typeof import('./components/the-preview.vue')['default']
  }
}

export { }
